import type { WithContext, FAQPage, HowToThing, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { PromptLibraryUI } from '../ui';

const slug = 'prywatna-biblioteka-sztucznej-inteligencji-prompt';
const title = 'Prywatna Biblioteka Promptów AI';
const description = 'Organizuj, taguj i zapisuj swoje prompty ChatGPT, Midjourney i Claude prywatnie. Twój własny bank promptów w localStorage.';

const faqData = [
  { question: 'Gdzie są zapisane moje prompty?', answer: 'Twoje prompty są zapisane wyłącznie w lokalnym przechowywaniu Twojej przeglądarki (localStorage). Nie używamy serwerów zewnętrznych, co oznacza, że Twoje dane są 100% prywatne.' },
  { question: 'Co się stanie, jeśli wyczyścę ciasteczka przeglądarki lub historię?', answer: 'Jeśli wyczyścisz dane witryny lub przechowywanie lokalne, utracisz zapisane prompty. Rekomendujemy tworzenie kopii zapasowych, jeśli regularnie czyścisz przeglądarkę.' },
  { question: 'Czy mogę używać tego narzędzia do Midjourney, ChatGPT lub DALL-E?', answer: 'Tak, jest kompatybilne z dowolnym typem instrukcji AI. Możesz tworzyć określone tagi do organizowania swoich poleceń i łatwo je kopiować do preferowanego narzędzia AI.' },
];

const howToData = [
  { name: 'Utwórz prompt', text: 'Kliknij przycisk Nowy Prompt i wpisz tytuł i instrukcję.' },
  { name: 'Dodaj tagi', text: 'Wpisz tagi oddzielone spacją lub przecinkiem, aby sklasyfikować swoje prompty.' },
  { name: 'Użyj zmiennych', text: 'Użyj nawiasów [TAKIE TO] w tekście, aby utworzyć pola do wypełnienia na karcie.' },
  { name: 'Kopiuj i udostępniaj', text: 'Skopiuj do schowka jednym kliknięciem lub udostępniaj bezpośredni link przyciskiem udostępniania.' },
];

const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqData.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowToThing> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howToData.map((s, i) => ({ '@type': 'HowToStep', position: i + 1, name: s.name, text: s.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'UtilityApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' }, inLanguage: 'pl' };

const ui: PromptLibraryUI = { placeholderSearch: 'Wyszukiwanie po słowie kluczowym lub tagu...', btnNew: 'Nowy Prompt', emptyTitle: 'Twoja biblioteka jest pusta', emptyDesc: 'Utwórz swój pierwszy prompt i zacznij budować prywatne repozytorium AI.', btnAddFirst: 'Dodaj pierwszy', modalTitleCreate: 'Utwórz Nowy Prompt', modalTitleEdit: 'Edytuj Prompt', labelTitle: 'Tytuł identyfikujący', placeholderTitle: 'Np.: Ekspert Marketingu SEO', labelContent: 'Instrukcja (Prompt)', placeholderContent: 'Wpisz tutaj szczegółowe instrukcje dla AI...', hintContent: 'Wskazówka: używaj nawiasów [TAKIE TO] do zmiennych, które wypełnisz później.', labelTags: 'Tagi', placeholderTags: 'Np.: marketing, seo (spacja lub przecinek do dodawania)', btnCancel: 'Anuluj', btnSave: 'Zapisz Lokalnie', ariaLabelStar: 'Oznacz prompt gwiazdką', ariaLabelEdit: 'Edytuj prompt', ariaLabelShare: 'Udostępniaj prompt', ariaLabelCopy: 'Kopiuj prompt', ariaLabelDelete: 'Usuń prompt', varsTitle: 'Wymagane zmienne', noResults: 'Nie znaleziono promptów dla tego wyszukiwania.', confirmTitle: 'Usunąć prompt?', confirmDesc: 'Tej akcji nie można cofnąć.', btnCancelDelete: 'Anuluj', btnConfirmDelete: 'Usuń permanentnie', };

export const content: ToolLocaleContent<PromptLibraryUI> = { slug, title, description, ui, faqTitle: 'Często Zadawane Pytania', faq: faqData, bibliographyTitle: 'Referencje Inżynierii Promptów', bibliography: [{ name: 'Prompt Engineering Guide (DAIR.AI)', url: 'https://www.promptingguide.ai/' }, { name: 'What is prompt engineering (Google Cloud)', url: 'https://cloud.google.com/discover/what-is-prompt-engineering' }], howTo: howToData, schemas: [faqSchema, howToSchema, appSchema], seo: [{ type: 'title', text: 'Dlaczego potrzebujesz biblioteki promptów?', level: 2 }, { type: 'paragraph', html: 'Jeśli regularnie pracujesz z narzędziami AI, takimi jak ChatGPT, Claude czy Midjourney, pewnie zauważyłeś, że powtarzasz te same instrukcje. <strong>Biblioteka promptów</strong> to ostateczne rozwiązanie, aby przestać zmarnować czas na przepisywanie ulubionych poleceń.' }, { type: 'title', text: 'Korzyści z organizowania promptów', level: 3 }, { type: 'list', items: ['<strong>Błyskawiczne wyszukiwanie:</strong> Znajdź tę konkretną instrukcję, którą używałeś miesiące temu, za pomocą prostego wyszukiwania tekstowego.', '<strong>Klasyfikacja tagami:</strong> Taguj prompty jako "marketing", "programowanie" czy "copywriting", aby szybko filtrować.', '<strong>Kopiowanie jednym kliknięciem:</strong> Skopiuj pełny tekst do schowka jednym kliknięciem.', '<strong>Całkowita prywatność:</strong> Wszystkie Twoje dane są przechowywane lokalnie w przeglądarce poprzez localStorage.'] }, { type: 'title', text: 'Zmienne w Twoich promptach', level: 3 }, { type: 'paragraph', html: 'Użyj notacji <strong>[ZMIENNA]</strong> w swoich promptach, aby tworzyć dynamicznie wypełnialne pola. Gdy otworzysz kartę, pojawią się pola wejściowe dla każdej zdefiniowanej zmiennej. Prompt jest kopiowany ze wypełnionymi wartościami, gotowy do wklejenia do swojego AI.' }, { type: 'title', text: 'Udostępnianie promptów', level: 3 }, { type: 'paragraph', html: 'Każdy prompt można udostępnić poprzez URL. Przycisk udostępniania generuje link, który po otwarciu pokazuje formularz tworzenia wstępnie wypełniony zawartością promptu.' }] };
