import type { WithContext, FAQPage, HowToThing, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { MusicalTypographyUI } from '../ui';

const slug = 'musikal-typografi-skal';
const title = 'Musikal Typografisk Skala. Modulär Skalakalkylator';
const description = 'Gratis onlineverktyg för att skapa harmoniska visuella hierarkier med modulära skalor baserade på musikaliska proportioner. Genererar redo-att-använda CSS-variabler för din webdesign.';

const faqData = [
  { question: 'Vad är en typografisk modulär skala?', answer: 'Det är en metod för att bestämma teckenstorlekar baserat på ett konstant matematiskt förhållande. Precis som i musik, där noter har harmoniska relationer, skapar den modulära skalan en balanserad och förutsebar visuell hierarki.' },
  { question: 'Varför använda musikaliska intervaller för design?', answer: 'Musikaliska intervaller är proportioner som den mänskliga hjärnan uppfattar som harmoniska. Att tillämpa dem på textstorlekar skapar en visuell struktur som känns korrekt och professionell, snarare än godtyckligt valda storlekar.' },
  { question: 'Vad är det gyllene snittet i typografi?', answer: 'Det är proportionen 1.618, känd som den gyllene sektionen. Det skapar mycket dramatiska och eleganta skalor där varje steg i hierarkin växer exponentiellt. Perfekt för portfölj- eller konstfokuserade webbplatser.' },
  { question: 'Hur implementerar jag skalan i min CSS-fil?', answer: 'Verktyget genererar CSS-variabler (tokens) i formatet :root { --step-N: Xrem; }. Kopiera dem till din huvudsakliga CSS-fil och använd dem med var(--step-N) för att bibehålla typografisk konsistens på din webbplats.' },
];

const howToData = [
  { name: 'Ställ in basstorlek', text: 'Ange teckenstorleken för din brödtext (vanligtvis 16px) som kommer att fungera som grundnoten i din skala.' },
  { name: 'Välj intervall', text: 'Välj en musikalisk proportion för att bestämma hur mycket utrymme det finns mellan olika rubriknivåer.' },
  { name: 'Förhandsgranska hierarkin', text: 'Titta i realtid på hur de typografiska nivåerna beter sig för att verifiera att den visuella harmonin passar ditt projekt.' },
  { name: 'Exportera koden', text: 'Klicka Kopiera CSS-variabler för att få blocket klart att klistra in direkt i ditt arbetsflöde.' },
];

const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqData.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowToThing> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howToData.map((step, i) => ({ '@type': 'HowToStep', position: i + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'DesignApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' }, inLanguage: 'sv' };

const ui: MusicalTypographyUI = { labelConfig: 'Konfiguration', labelBaseSize: 'Basstorlek (px)', hintBaseSize: 'Din styckestextstorlek (vanligtvis 16px).', labelRatio: 'Musikal Skala (Förhållande)', hintRatio: 'Bestämmer hur mycket storleken växer vid varje steg.', labelCalculated: 'Beräknade Värden', labelPreview: 'Förhandsvisning', btnCopyCss: 'Kopiera CSS-Variabler', feedbackCopied: 'Variabler kopierade till urklipp!', previewText: 'Musikal Typografi', previewSubtext: 'En perfekt harmonisk skala för din design.', ratioSecundaMenor: 'Liten Sekund', ratioSegundaMayor: 'Stor Sekund', ratioTerceraMenor: 'Liten Ters', ratioTerceraMayor: 'Stor Ters', ratioCuartaPerfecta: 'Perfekt Fjärdedel', ratioCuartaAumentada: 'Utökad Fjärdedel', ratioQuintaPerfecta: 'Perfekt Kvint', ratioProporcionAurea: 'Gyllene Snitt', ratioSextaMayor: 'Stor Sext', ratioSeptimaMenor: 'Liten Septim', ratioSeptimaMayor: 'Stor Septim', ratioOctava: 'Oktav' };

export const content: ToolLocaleContent<MusicalTypographyUI> = { slug, title, description, ui, faqTitle: 'Vanliga Frågor', faq: faqData, bibliographyTitle: 'Referenser', bibliography: [{ name: 'Bringhurst, R. The Elements of Typographic Style', url: 'https://en.wikipedia.org/wiki/The_Elements_of_Typographic_Style' }, { name: 'Brown, T. More Meaningful Typography. A List Apart', url: 'https://alistapart.com/article/more-meaningful-typography/' }, { name: 'Physics of Music. Musical Intervals and Scales', url: 'https://es.scribd.com/document/199729396/Physics-of-Music-Notes' }], howTo: howToData, schemas: [faqSchema, howToSchema, appSchema], seo: [{ type: 'title', text: 'Den osynliga harmonin inom webdesign', level: 2 }, { type: 'paragraph', html: 'Den <strong>Musikala Typografiska Skalan</strong> tillämpar matematiken för musikaliska intervaller på typografisk design. Precis som en musikkomposition styrs av exakta proportioner, gynnas en solid design av en matematisk struktur som relaterar alla storlekar till varandra.' }, { type: 'title', text: 'Hur den modulära skalan fungerar', level: 3 }, { type: 'grid', columns: 2 }, { type: 'card', title: 'Formeln', html: '<p>Progressionen är enkel: <code>Size = Base × Ratio<sup>n</sup></code>. Steg 0 är din bastex. Steg 1 är en liten undertext. Steg 4 eller 5 kan vara din huvudsakliga H1. Samma multiplikationskonstant (förhållandet) säkerställer att alla relationer är konsekventa.</p>' }, { type: 'card', title: 'Varför "Musikal"', html: '<p>Pythagoreerna upptäckte att delning av en sträng i enkla proportioner (1:2, 2:3, 3:4) producerade konsonanta ljud. Dessa intervaller, oktav, perfekt kvint och perfekt fjärdedel, är exakt de typografiska proportionerna. Du komponerar visuell musik.</p>' }, { type: 'title', text: 'Att välja rätt förhållande', level: 3 }, { type: 'tip', html: 'För täta gränssnitt (instrumentpaneler, tabeller) använd små förhållanden som <code>1.125</code> eller <code>1.2</code>. För redaktionella eller portföljwebbplatser, använd mer uttrycksfulla förhållanden som <code>1.5</code> eller <code>1.618</code>.' }, { type: 'paragraph', html: 'Begränsa inte skalan till bara <code>font-size</code>. Samma CSS-variabler fungerar för <code>margin</code>, <code>padding</code> och <code>gap</code>. När tomt utrymme följer samma matematiska progression som texten, uppnår designen en nivå av sammanhållning som alla känner men få kan förklara.' }] };
