import type { WithContext, FAQPage, HowToThing, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { MusicalTypographyUI } from '../ui';

const slug = 'muziksal-tipografi-olcegi';
const title = 'Müziksel Tipografi Ölçeği. Modüler Ölçek Hesaplayıcısı';
const description = 'Müziksel oranlarına dayalı modüler ölçekler kullanarak uyumlu görsel hiyerarşiler oluşturmak için ücretsiz çevrimiçi araç. Web tasarımınız için kullanıma hazır CSS değişkenleri oluşturur.';

const faqData = [
  { question: 'Tipografik modüler ölçek nedir?', answer: 'Sabit bir matematiksel orana dayalı olarak yazı tipi boyutlarını belirleme yöntemidir. Müzikte notaların uyumlu ilişkileri olduğu gibi, modüler ölçek dengeli ve öngörülebilir bir görsel hiyerarşi oluşturur.' },
  { question: 'Tasarımda neden müzik intervallerini kullanmalı?', answer: 'Müzik aralıkları, insan beyninin uyumlu olarak algıladığı oranlarıdır. Bunları metin boyutlarına uygulamak, rastgele seçilen boyutlar yerine doğru ve profesyonel hissettiren bir görsel yapı oluşturur.' },
  { question: 'Tipografide Altın Oran nedir?', answer: '1.618 oranıdır, Altın Bölüm olarak bilinir. Hiyerarşideki her adım üstel olarak büyüyen çok dramatik ve zarif ölçekler oluşturur. Portföy veya sanat odaklı web siteleri için mükemmeldir.' },
  { question: 'CSS dosyamda ölçeği nasıl uygularım?', answer: 'Araç, :root { --step-N: Xrem; } biçiminde CSS değişkenleri (tokens) oluşturur. Bunları ana CSS dosyanıza kopyalayın ve web sitenizde tipografik tutarlılığı sağlamak için var(--step-N) ile kullanın.' },
];

const howToData = [
  { name: 'Temel boyutu ayarlayın', text: 'Gövde metninizin yazı tipi boyutunu (genellikle 16px) girin, bu sizin ölçeğinizin temel notası olacak.' },
  { name: 'Aralığı seçin', text: 'Farklı başlık seviyeleri arasında ne kadar alan olduğunu belirlemek için müzik oranı seçin.' },
  { name: 'Hiyerarşiyi önizleyin', text: 'Görsel harmoni tasarımınıza uygun olduğunu doğrulamak için tipografik seviyelerin gerçek zamanlı nasıl davrandığını izleyin.' },
  { name: 'Kodu dışa aktarın', text: 'Iş akışınıza doğrudan yapıştırmaya hazır blok almak için CSS Değişkenlerini Kopyala\'ya tıklayın.' },
];

const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqData.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowToThing> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howToData.map((step, i) => ({ '@type': 'HowToStep', position: i + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'DesignApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' }, inLanguage: 'tr' };

const ui: MusicalTypographyUI = { labelConfig: 'Yapılandırma', labelBaseSize: 'Temel Boyut (px)', hintBaseSize: 'Paragraf metin boyutunuz (genellikle 16px).', labelRatio: 'Müzik Ölçeği (Oran)', hintRatio: 'Boyutun her adımda ne kadar büyüdüğünü belirler.', labelCalculated: 'Hesaplanan Değerler', labelPreview: 'Önizleme', btnCopyCss: 'CSS Değişkenlerini Kopyala', feedbackCopied: 'Değişkenler panoya kopyalandı!', previewText: 'Müziksel Tipografi', previewSubtext: 'Tasarımınız için mükemmel uyumlu ölçek.', ratioSecundaMenor: 'Küçük İkinci', ratioSegundaMayor: 'Büyük İkinci', ratioTerceraMenor: 'Küçük Üçüncü', ratioTerceraMayor: 'Büyük Üçüncü', ratioCuartaPerfecta: 'Mükemmel Dördüncü', ratioCuartaAumentada: 'Arttırılmış Dördüncü', ratioQuintaPerfecta: 'Mükemmel Beşinci', ratioProporcionAurea: 'Altın Oran', ratioSextaMayor: 'Büyük Altıncı', ratioSeptimaMenor: 'Küçük Yedinci', ratioSeptimaMayor: 'Büyük Yedinci', ratioOctava: 'Sekizinci' };

export const content: ToolLocaleContent<MusicalTypographyUI> = { slug, title, description, ui, faqTitle: 'Sık Sorulan Sorular', faq: faqData, bibliographyTitle: 'Referanslar', bibliography: [{ name: 'Bringhurst, R. The Elements of Typographic Style', url: 'https://en.wikipedia.org/wiki/The_Elements_of_Typographic_Style' }, { name: 'Brown, T. More Meaningful Typography. A List Apart', url: 'https://alistapart.com/article/more-meaningful-typography/' }, { name: 'Physics of Music. Musical Intervals and Scales', url: 'https://es.scribd.com/document/199729396/Physics-of-Music-Notes' }], howTo: howToData, schemas: [faqSchema, howToSchema, appSchema], seo: [{ type: 'title', text: 'Web Tasarımının Görünmez Uyumu', level: 2 }, { type: 'paragraph', html: '<strong>Müziksel Tipografi Ölçeği</strong> müzik aralıklarının matematiğini tipografik tasarıma uygular. Müzik bestesi kesin oranlarla yönetildiği gibi, iyi tasarım tüm boyutları birbiriyle ilişkilendiren matematiksel bir yapıdan yararlanır.' }, { type: 'title', text: 'Modüler ölçek nasıl çalışır', level: 3 }, { type: 'grid', columns: 2 }, { type: 'card', title: 'Formül', html: '<p>İlerleme basittir: <code>Size = Base × Ratio<sup>n</sup></code>. Adım 0, temel metniniz. Adım 1, küçük bir altyazı. Adım 4 veya 5, ana H1\'iniz olabilir. Aynı çarpma sabiti (oran) tüm ilişkilerin tutarlı olmasını sağlar.</p>' }, { type: 'card', title: 'Neden "Müziksel"', html: '<p>Pythagorası, bir dizeyi basit oranlara (1:2, 2:3, 3:4) böldüğünde uyumlu sesler üretileceğini keşfetti. Bu aralıklar, sekizinci, mükemmel beşinci ve mükemmel dördüncü, tam olarak tipografik oranlarıdır. Görsel müzik besteliyorsunuz.</p>' }, { type: 'title', text: 'Doğru oranı seçme', level: 3 }, { type: 'tip', html: 'Yoğun arayüzler (panolar, tablolar) için <code>1.125</code> veya <code>1.2</code> gibi küçük oranlar kullanın. Editoryal veya portföy siteleri için <code>1.5</code> veya <code>1.618</code> gibi daha anlatımlı oranlar kullanın.' }, { type: 'paragraph', html: 'Ölçeği sadece <code>font-size</code> ile sınırlamayın. Aynı CSS değişkenleri <code>margin</code>, <code>padding</code> ve <code>gap</code> için çalışır. Boş alan, metin ile aynı matematiksel ilerlemeyi takip ettiğinde, tasarım herkesin hissettiği ancak çok azının açıklayabileceği bir tutarlılık düzeyine ulaşır.' }] };
