import type { WithContext, FAQPage, HowToThing, SoftwareApplication } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { ReadabilityCalculatorUI } from '../ui';

const slug = 'visual-readability-calculator-wcag-apca';
const title = 'Visual Readability Calculator WCAG and APCA';
const description = 'Check the real contrast of your designs with APCA (WCAG 3.0). Analyze how font weight and size affect actual readability. From simple ratios to perceptual legibility.';

const faqData = [
  {
    question: 'What is APCA and why is it different from WCAG 2.1?',
    answer: 'APCA is the Advanced Perceptual Contrast Algorithm developed for WCAG 3.0. Unlike the old simple ratio, APCA uses mathematical models that mimic how the human brain perceives contrast, taking into account polarity (light vs. dark background) and font size/weight.',
  },
  {
    question: 'What does the Lc value mean?',
    answer: 'Lc (Lightness Contrast) is the contrast value generated by APCA. A value of 100 represents ideal maximum contrast, while values below 60 start to be critical for continuous reading text. It is an absolute magnitude scale of perception.',
  },
  {
    question: 'How does font weight affect readability?',
    answer: 'Thin/Light fonts require much higher contrast to be readable. APCA penalizes low-weight fonts, indicating that a design passing WCAG with a weight-100 font may be illegible in practice.',
  },
  {
    question: 'Is this calculator private?',
    answer: 'Yes, all calculations are performed locally in your browser. The colors and settings you analyze are never sent to any server, guaranteeing full privacy for your design projects.',
  },
];

const howToData = [
  { name: 'Choose Colors', text: 'Use the color pickers to set the text color and background color of your design.' },
  { name: 'Adjust Typography', text: 'Move the font size and weight sliders to simulate your actual typography.' },
  { name: 'Read the Results', text: 'Check the WCAG 2.1 ratio and the APCA Lc value to know if your design is accessible.' },
  { name: 'Review Recommendations', text: 'Check APCA-specific recommendations for body text, small text and UI elements.' },
];

const faqSchema: WithContext<FAQPage> = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqData.map((item) => ({
    '@type': 'Question',
    name: item.question,
    acceptedAnswer: { '@type': 'Answer', text: item.answer },
  })),
};

const howToSchema: WithContext<HowToThing> = {
  '@context': 'https://schema.org',
  '@type': 'HowTo',
  name: title,
  description,
  step: howToData.map((s, i) => ({ '@type': 'HowToStep', position: i + 1, name: s.name, text: s.text })),
};

const appSchema: WithContext<SoftwareApplication> = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: title,
  description,
  applicationCategory: 'UtilityApplication',
  operatingSystem: 'All',
  offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' },
  inLanguage: 'en',
};

const ui: ReadabilityCalculatorUI = {
  labelColors: 'Base Colors',
  labelText: 'Text',
  labelBg: 'Background',
  labelTypo: 'Typography',
  labelFontSize: 'Font Size',
  labelFontWeight: 'Weight',
  labelCompare: 'Contrast Comparison',
  labelPreview: 'Perceptual Preview',
  labelApcaRecs: 'APCA Recommendations',
  labelBody: 'Reading Text (Body)',
  labelSmall: 'Small Text / Caption',
  labelUi: 'UI / Buttons',
  statusYes: 'Yes',
  statusNo: 'No',
  wcagAAA: 'Passes AAA',
  wcagAA: 'Passes AA',
  wcagLarge: 'Large Text Only',
  wcagFail: 'Fails',
  apcaExcellent: 'Excellent',
  apcaGood: 'Good',
  apcaMinimal: 'Minimal',
  apcaPoor: 'Poor',
  previewText: 'Visual readability is not just mathematics. It is how light and shadow interact with your eyes.',
  wcagRatioLabel: 'WCAG 2.1 Ratio',
  apcaLcLabel: 'APCA Lc (WCAG 3)',
};

export const content: ToolLocaleContent<ReadabilityCalculatorUI> = {
  slug,
  title,
  description,
  ui,
  faqTitle: 'Frequently Asked Questions',
  faq: faqData,
  bibliographyTitle: 'Resources on Contrast and APCA',
  bibliography: [
    { name: 'W3C: WCAG 3.0 Draft (Silver)', url: 'https://www.w3.org/WAI/standards-guidelines/wcag/wcag3-intro/' },
    { name: 'Myndex: APCA Reference Guide', url: 'https://apcaw3.myndex.com/' },
    { name: 'MDN: Accessibility and Color Contrast', url: 'https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast' },
  ],
  howTo: howToData,
  schemas: [faqSchema, howToSchema, appSchema],
  seo: [
    { type: 'title', text: 'Visual Readability Calculator (WCAG vs APCA)', level: 2 },
    {
      type: 'paragraph',
      html: 'Understand how your colors and typography affect actual reading with the new perceptual accessibility standard. WCAG 2.1 uses a simple 2008 mathematical formula. <strong>APCA</strong> is the new model proposed for <strong>WCAG 3.0</strong> that mimics human perception.',
    },
    { type: 'title', text: 'Key Points of APCA', level: 3 },
    {
      type: 'list',
      items: [
        '<strong>Polarity:</strong> Understands that Dark Mode is perceived differently than Light Mode.',
        '<strong>Font Weight:</strong> Assigns specific contrast levels (Lc) based on typography weight.',
        '<strong>Linearity:</strong> Fixes mathematical inaccuracies in the 2008 relative luminance model.',
      ],
    },
    { type: 'title', text: 'Recommended APCA Levels', level: 3 },
    {
      type: 'list',
      items: [
        '<strong>Lc 90+:</strong> Ideal for very small or low-weight text.',
        '<strong>Lc 75:</strong> The standard for main body reading text.',
        '<strong>Lc 60:</strong> Minimum for readable medium-size content.',
        '<strong>Lc 45:</strong> Minimum for large or decorative elements.',
      ],
    },
  ],
};
