export { aspectRatio } from './tool/aspectRatio/entry';
export type { AspectRatioLocaleContent } from './tool/aspectRatio/entry';
export { calculadoraTiempoDatos } from './tool/calculadoraTiempoDatos/entry';
export type { CalculadoraTiempoDatosLocaleContent } from './tool/calculadoraTiempoDatos/entry';
export { colorConverter } from './tool/colorConverter/entry';
export type { ColorConverterLocaleContent } from './tool/colorConverter/entry';
export { conversorExcelCsvHtml } from './tool/conversorExcelCsvHtml/entry';
export type { ConversorExcelCsvHtmlLocaleContent } from './tool/conversorExcelCsvHtml/entry';
export { cronGenerator } from './tool/cronGenerator/entry';
export type { CronGeneratorLocaleContent } from './tool/cronGenerator/entry';
export { cssSpecificityCalculator } from './tool/cssSpecificityCalculator/entry';
export type { CssSpecificityCalculatorLocaleContent } from './tool/cssSpecificityCalculator/entry';
export { cssToInlineConverter } from './tool/cssToInlineConverter/entry';
export type { CssToInlineConverterLocaleContent } from './tool/cssToInlineConverter/entry';
export { duplicateCssRemover } from './tool/duplicateCssRemover/entry';
export type { DuplicateCssRemoverLocaleContent } from './tool/duplicateCssRemover/entry';
export { generadorSecurityTxt } from './tool/generadorSecurityTxt/entry';
export type { GeneradorSecurityTxtLocaleContent } from './tool/generadorSecurityTxt/entry';
export { hashGenerator } from './tool/hashGenerator/entry';
export type { HashGeneratorLocaleContent } from './tool/hashGenerator/entry';
export { inspectorCertificadosSsl } from './tool/inspectorCertificadosSsl/entry';
export type { InspectorCertificadosSslLocaleContent } from './tool/inspectorCertificadosSsl/entry';
export { jsonFormatter } from './tool/jsonFormatter/entry';
export type { JsonFormatterLocaleContent } from './tool/jsonFormatter/entry';
export { keycode } from './tool/keycode/entry';
export type { KeycodeLocaleContent } from './tool/keycode/entry';
export { llmCostCalculator } from './tool/llmCostCalculator/entry';
export type { LlmCostCalculatorLocaleContent } from './tool/llmCostCalculator/entry';
export { mobileMockupGenerator } from './tool/mobileMockupGenerator/entry';
export type { MobileMockupGeneratorLocaleContent } from './tool/mobileMockupGenerator/entry';
export { musicalTypography } from './tool/musicalTypography/entry';
export type { MusicalTypographyLocaleContent } from './tool/musicalTypography/entry';
export { placeholderGenerator } from './tool/placeholderGenerator/entry';
export type { PlaceholderGeneratorLocaleContent } from './tool/placeholderGenerator/entry';
export { promptLibrary } from './tool/promptLibrary/entry';
export type { PromptLibraryLocaleContent } from './tool/promptLibrary/entry';
export { readabilityCalculator } from './tool/readabilityCalculator/entry';
export type { ReadabilityCalculatorLocaleContent } from './tool/readabilityCalculator/entry';
export { svgSanitizer } from './tool/svgSanitizer/entry';
export type { SvgSanitizerLocaleContent } from './tool/svgSanitizer/entry';
export { svgToCss } from './tool/svgToCss/entry';
export type { SvgToCssLocaleContent } from './tool/svgToCss/entry';
export { urlCleaner } from './tool/urlCleaner/entry';
export type { UrlCleanerLocaleContent } from './tool/urlCleaner/entry';
export { urlEncoderDecoder } from './tool/urlEncoderDecoder/entry';
export type { UrlEncoderDecoderLocaleContent } from './tool/urlEncoderDecoder/entry';
export { utmGenerator } from './tool/utmGenerator/entry';
export type { UtmGeneratorLocaleContent } from './tool/utmGenerator/entry';
export { developerCategory } from './category';
import { aspectRatio } from './tool/aspectRatio/entry';
import { calculadoraTiempoDatos } from './tool/calculadoraTiempoDatos/entry';
import { colorConverter } from './tool/colorConverter/entry';
import { conversorExcelCsvHtml } from './tool/conversorExcelCsvHtml/entry';
import { cronGenerator } from './tool/cronGenerator/entry';
import { cssSpecificityCalculator } from './tool/cssSpecificityCalculator/entry';
import { cssToInlineConverter } from './tool/cssToInlineConverter/entry';
import { duplicateCssRemover } from './tool/duplicateCssRemover/entry';
import { generadorSecurityTxt } from './tool/generadorSecurityTxt/entry';
import { hashGenerator } from './tool/hashGenerator/entry';
import { inspectorCertificadosSsl } from './tool/inspectorCertificadosSsl/entry';
import { jsonFormatter } from './tool/jsonFormatter/entry';
import { keycode } from './tool/keycode/entry';
import { llmCostCalculator } from './tool/llmCostCalculator/entry';
import { mobileMockupGenerator } from './tool/mobileMockupGenerator/entry';
import { musicalTypography } from './tool/musicalTypography/entry';
import { placeholderGenerator } from './tool/placeholderGenerator/entry';
import { promptLibrary } from './tool/promptLibrary/entry';
import { readabilityCalculator } from './tool/readabilityCalculator/entry';
import { svgSanitizer } from './tool/svgSanitizer/entry';
import { svgToCss } from './tool/svgToCss/entry';
import { urlCleaner } from './tool/urlCleaner/entry';
import { urlEncoderDecoder } from './tool/urlEncoderDecoder/entry';
import { utmGenerator } from './tool/utmGenerator/entry';
export const ALL_ENTRIES = [aspectRatio, calculadoraTiempoDatos, colorConverter, conversorExcelCsvHtml, cronGenerator, cssSpecificityCalculator, cssToInlineConverter, duplicateCssRemover, generadorSecurityTxt, hashGenerator, inspectorCertificadosSsl, jsonFormatter, keycode, llmCostCalculator, mobileMockupGenerator, musicalTypography, placeholderGenerator, promptLibrary, readabilityCalculator, svgSanitizer, svgToCss, urlCleaner, urlEncoderDecoder, utmGenerator];
